### ISSUE TITLE
bound box altered

### ISSUE THREAD

**Issue by fuentesdt** [aecelaya/MIST#22]
The bounding box of the output segmentation is altered from the original image. This causes downstream problems with packages like pyradiomics

$ c3d Art.raw.nii.gz -info Art.liver.nii.gz -info
Image #1: dim = [320, 258, 88];  bb = {[-197.665 -169.311 -96.9695], [222.335 169.314 167.03]};  vox = [1.3125, 1.3125, 3];  range = [0, 543];  orient = Oblique, closest to RAI

Image #2: dim = [320, 258, 88];  bb = {[-201.603 -188.998 -96.9766], [218.397 149.627 167.023]};  vox = [1.3125, 1.3125, 3];  range = [0, 1];  orient = Oblique, closest to RAI

**Comment by aecelaya** [comment]
Can you try the -mbb flag with c3d?

c3d reference.nii target.nii -mbb -o out.nii

**Comment by aecelaya** [comment]
The latest release should address this issue. Let me know if it persists.
