### ISSUE TITLE
How to improve dice score with Lits

### ISSUE THREAD

**Issue by rachelglenn** [aecelaya/MIST#5]
I ran the tensorflow code with the Lits data with the flags

nnunet --pocket --xla -amp --patch-size 128 128 128 epochs 125 

and I got the following results

Mean,     0.8993201019273616
Std,      0.1050104076908201
25th Percentile,     0.8935995292553426
Median,    0.9303144316101752
75th Percentile,    0.9463229317287942

How can I improve the mean dice score?

Thanks,

Rachel

**Comment by aecelaya** [comment]
I'd recommend more epochs and also try postprocessing the predictions by taking the largest component. I'll try these and a couple of other things and get back to you. Are you running a five fold cross validation?
