### ISSUE TITLE
instabilty on large number of labels N=80

### ISSUE THREAD

**Issue by fuentesdt** [aecelaya/MIST#6]

**Comment by evanmlim** [comment]
For N = 8 labels, the model fails to identify certain regions and/or mislabels certain regions. I have not tested this with N=80 labels yet.

Parameters:
--epochs 60
--fold 0
--pocket True
--amp True
--model nnunet (btw, what is the default model? It's not listed in documentation)
all else default

Labels:
[0,1,2,3,4,5,6,7,8]
hyoid: 1, ln_neck_vib: 2, oropharynx: 3, oral_cavity: 4, lips: 5, ln_neck_via: 6, jugular_vein_r: 7, jugular_vein_l: 8
 
Example (ground truth left, prediction right)
![image](https://github.com/aecelaya/MIST/assets/60450731/75a75ca4-1b2c-4d76-8504-f45db95accc4)

The model fails to predict 6 of the 8 labels:
![image](https://github.com/aecelaya/MIST/assets/60450731/af746000-2185-4a62-bd90-c4c5aab80f88)

A similar result occurs across all predictions.

The mislabeling of certain regions occurred in another model when I used prime numbers for the labels. In this case, the labels were:
[0,2,3,5,7,11,13,17,19]
hyoid: 2, ln_neck_vib: 3, oropharynx: 5, oral_cavity: 7, lips: 11, ln_neck_via: 13, jugular_vein_r: 17, jugular_vein_l: 19

Example image:
![image](https://github.com/aecelaya/MIST/assets/60450731/117b8ad7-cc7d-4aae-b437-de46e3ef28c0)
The model identified the oral cavity as label 17 despite the label for the oral cavity actually being 7. Similarly, this model also failed to use 6 of the 8 labels.

Overall, further testing is needed. The model didn't have issues at 1-2 labels (and it shouldn't considering that BraTS with 3 labels didn't have problems). This problem might also be specific to the dataset I'm using or something more fundamental.

**Comment by aecelaya** [comment]
Can you send me a path to the data please? I want to try this for myself to see what's happening

**Comment by aecelaya** [comment]
Looks like the following parameters fixed the predictions with N=8:

--patch-size 256 256 128
--epochs 300
--model nnunet
--pocket
--amp
--vae-reg

Like I said earlier, the data can be cropped down, which should help improve results/performance. Memory might become an issue with N=80 with a large patch size though.
